package com.pej.domains;
// Generated 30 oct. 2016 22:13:12 by Hibernate Tools 5.2.0.Beta1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Agent generated by hbm2java
 */
@Entity
@Table(name="AGENT"
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Agent  implements java.io.Serializable {


     private Integer idagent;
     private String nom;
     private String prenom;
     @DateTimeFormat(pattern = "dd/MM/yyyy")
     private Date datenaissance;
     private String sexe;
     private String cardid;
     private String telephone;
     private String numeroagent;
     @JsonIgnore
     private Antenne antenne;
     @JsonIgnore
     private Set<Candidat> candidats = new HashSet<Candidat>(0);

    public Agent() {
    }

	
    public Agent(Integer idagent) {
        this.idagent = idagent;
    }
    public Agent(Integer idagent, String nom, String prenom, Date datenaissance, String sexe, String cardid, String telephone, Set<Candidat> candidats) {
       this.idagent = idagent;
       this.nom = nom;
       this.prenom = prenom;
       this.datenaissance = datenaissance;
       this.sexe = sexe;
       this.cardid = cardid;
       this.telephone = telephone;
       this.candidats = candidats;
    }
   
     @Id 

 	@GeneratedValue(generator = "SEQ_IDAGENT", strategy = GenerationType.SEQUENCE)
 	@SequenceGenerator(name = "SEQ_IDAGENT", sequenceName = "SEQ_IDAGENT",allocationSize=1)
    @Column(name="IDAGENT", unique=true, nullable=false, precision=22, scale=0)
    public Integer getIdagent() {
        return this.idagent;
    }
    
    public void setIdagent(Integer idagent) {
        this.idagent = idagent;
    }

    
    @Column(name="NOM", length=100)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }


    @Column(name="PRENOM", length=100)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATENAISSANCE", length=7)
    public Date getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }

    
    @Column(name="SEXE", length=50)
    public String getSexe() {
        return this.sexe;
    }
    
    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    
    @Column(name="CARDID", length=20)
    public String getCardid() {
        return this.cardid;
    }
    
    public void setCardid(String cardid) {
        this.cardid = cardid;
    }

    
    @Column(name="TELEPHONE", length=20)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    @Column(name="NUMEROAGENT", length=20)
    public String getNumeroagent() {
		return numeroagent;
	}


	public void setNumeroagent(String numeroagent) {
		this.numeroagent = numeroagent;
	}


    @OneToMany(fetch=FetchType.LAZY, mappedBy="agent")
    public Set<Candidat> getCandidats() {
        return this.candidats;
    }
    
    public void setCandidats(Set<Candidat> candidats) {
        this.candidats = candidats;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDANTENNE")
	public Antenne getAntenne() {
		return antenne;
	}


	public void setAntenne(Antenne antenne) {
		this.antenne = antenne;
	}

	@Transient
	public String getIdentite(){
        if(this.prenom == null) return this.nom;
        else return this.nom+ " " + this.prenom;
    }




}


