package com.pej.domains;
// Generated 6 oct. 2016 04:12:45 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.*;


import java.io.Serializable;
/**
 * Arrondissement generated by hbm2java
 */
@Entity
@Table(name = "ARRONDISSEMENT", schema = "ADMINPEJ")
public class Arrondissement implements java.io.Serializable {

	private Integer codearrondissement;
	private Commune commune;
	private String libarrondissement;
	private String description;

	public Arrondissement() {
	}

	public Arrondissement(Integer codearrondissement, String libarrondissement) {
		this.codearrondissement = codearrondissement;
		this.libarrondissement = libarrondissement;
	}

	public Arrondissement(Integer codearrondissement, Commune commune, String libarrondissement, String description) {
		this.codearrondissement = codearrondissement;
		this.commune = commune;
		this.libarrondissement = libarrondissement;
		this.description = description;
	}

	@Id
	@GeneratedValue
	@Column(name = "CODEARRONDISSEMENT", unique = true, nullable = false, length = 20)
	public Integer getCodearrondissement() {
		return this.codearrondissement;
	}

	public void setCodearrondissement(Integer codearrondissement) {
		this.codearrondissement = codearrondissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODECOMMUNE")
	public Commune getCommune() {
		return this.commune;
	}

	public void setCommune(Commune commune) {
		this.commune = commune;
	}

	@Column(name = "LIBARRONDISSEMENT", nullable = false, length = 20)
	public String getLibarrondissement() {
		return this.libarrondissement;
	}

	public void setLibarrondissement(String libarrondissement) {
		this.libarrondissement = libarrondissement;
	}

	@Column(name = "DESCRIPTION", length = 20)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
