package com.pej.domains;
// Generated 30 oct. 2016 22:13:12 by Hibernate Tools 5.2.0.Beta1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Arrondissement generated by hbm2java
 */
@Entity
@Table(name="ARRONDISSEMENT"
)
public class Arrondissement  implements java.io.Serializable {


     private Integer codearrondissement;
     @JsonIgnore
     private Commune commune;
     private String libarrondissement;
     private String description;
     private Set<Quartier> quartiers = new HashSet<Quartier>(0);
    public Arrondissement() {
    }

	
    public Arrondissement(Integer codearrondissement, String libarrondissement) {
        this.codearrondissement = codearrondissement;
        this.libarrondissement = libarrondissement;
    }
    public Arrondissement(Integer codearrondissement, Commune commune, String libarrondissement, String description) {
       this.codearrondissement = codearrondissement;
       this.commune = commune;
       this.libarrondissement = libarrondissement;
       this.description = description;
    }
   
     @Id 
  	@GeneratedValue(generator = "SEQ_CODEARRONDISSEMENT", strategy = GenerationType.SEQUENCE)
  	@SequenceGenerator(name = "SEQ_CODEARRONDISSEMENT", sequenceName = "SEQ_CODEARRONDISSEMENT",allocationSize=1)
    
    @Column(name="CODEARRONDISSEMENT", unique=true, nullable=false, length=1024)
    public Integer getCodearrondissement() {
        return this.codearrondissement;
    }
    
    public void setCodearrondissement(Integer codearrondissement) {
        this.codearrondissement = codearrondissement;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODECOMMUNE")
    public Commune getCommune() {
        return this.commune;
    }
    
    public void setCommune(Commune commune) {
        this.commune = commune;
    }

    
    @Column(name="LIBARRONDISSEMENT", nullable=false, length=1024)
    public String getLibarrondissement() {
        return this.libarrondissement;
    }
    
    public void setLibarrondissement(String libarrondissement) {
        this.libarrondissement = libarrondissement;
    }

    
    @Column(name="DESCRIPTION", length=1024)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="arrondissement")
    public Set<Quartier> getQuartiers() {
        return this.quartiers;
    }
    
    public void setQuartiers(Set<Quartier> quartiers) {
        this.quartiers = quartiers;
    }


}


