package com.pej.domains;
// Generated 30 oct. 2016 22:13:12 by Hibernate Tools 5.2.0.Beta1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Beneficiairedon generated by hbm2java
 */
@Entity
@Table(name="BENEFICIAIREDON"
)
public class Beneficiairedon  implements java.io.Serializable {


     private BigDecimal idbeneficiairedon;
     private Beneficiaire beneficiaire;
     private Don don;
     private Date dateaccord;

    public Beneficiairedon() {
    }

	
    public Beneficiairedon(BigDecimal idbeneficiairedon) {
        this.idbeneficiairedon = idbeneficiairedon;
    }
    public Beneficiairedon(BigDecimal idbeneficiairedon, Beneficiaire beneficiaire, Don don, Date dateaccord) {
       this.idbeneficiairedon = idbeneficiairedon;
       this.beneficiaire = beneficiaire;
       this.don = don;
       this.dateaccord = dateaccord;
    }
   
     @Id 

    
    @Column(name="IDBENEFICIAIREDON", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdbeneficiairedon() {
        return this.idbeneficiairedon;
    }
    
    public void setIdbeneficiairedon(BigDecimal idbeneficiairedon) {
        this.idbeneficiairedon = idbeneficiairedon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDBENEFICIAIRE")
    public Beneficiaire getBeneficiaire() {
        return this.beneficiaire;
    }
    
    public void setBeneficiaire(Beneficiaire beneficiaire) {
        this.beneficiaire = beneficiaire;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDDON")
    public Don getDon() {
        return this.don;
    }
    
    public void setDon(Don don) {
        this.don = don;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEACCORD", length=7)
    public Date getDateaccord() {
        return this.dateaccord;
    }
    
    public void setDateaccord(Date dateaccord) {
        this.dateaccord = dateaccord;
    }




}


