package com.pej.domains;
// Generated 30 oct. 2016 22:13:12 by Hibernate Tools 5.2.0.Beta1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Beneficiaire generated by hbm2java
 */
@Entity
@Table(name="BENEFICIAIRE"
)
public class Beneficiaire  implements java.io.Serializable {


     private BigDecimal idbeneficiaire;
     private Candidat candidat;
     private Date dateselection;
     private String remarque;
     private BigDecimal iduser;
     private String column1;
    // private Set<Formationbeneficaire> formationbeneficaires = new HashSet<Formationbeneficaire>(0);
     private Set<Beneficiairedon> beneficiairedons = new HashSet<Beneficiairedon>(0);
     //private Set<Beneficiairecooperative> beneficiairecooperatives = new HashSet<Beneficiairecooperative>(0);

    public Beneficiaire() {
    }

	
    public Beneficiaire(BigDecimal idbeneficiaire) {
        this.idbeneficiaire = idbeneficiaire;
    }
    public Beneficiaire(BigDecimal idbeneficiaire, Candidat candidat, Date dateselection, String remarque, BigDecimal iduser, String column1, Set<Formationbeneficaire> formationbeneficaires, Set<Beneficiairedon> beneficiairedons, Set<Beneficiairecooperative> beneficiairecooperatives) {
       this.idbeneficiaire = idbeneficiaire;
       this.candidat = candidat;
       this.dateselection = dateselection;
       this.remarque = remarque;
       this.iduser = iduser;
       this.column1 = column1;
       //this.formationbeneficaires = formationbeneficaires;
       this.beneficiairedons = beneficiairedons;
       //this.beneficiairecooperatives = beneficiairecooperatives;
    }
   
     @Id 

    
    @Column(name="IDBENEFICIAIRE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdbeneficiaire() {
        return this.idbeneficiaire;
    }
    
    public void setIdbeneficiaire(BigDecimal idbeneficiaire) {
        this.idbeneficiaire = idbeneficiaire;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCANDIDAT")
    public Candidat getCandidat() {
        return this.candidat;
    }
    
    public void setCandidat(Candidat candidat) {
        this.candidat = candidat;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATESELECTION", length=7)
    public Date getDateselection() {
        return this.dateselection;
    }
    
    public void setDateselection(Date dateselection) {
        this.dateselection = dateselection;
    }

    
    @Column(name="REMARQUE")
    public String getRemarque() {
        return this.remarque;
    }
    
    public void setRemarque(String remarque) {
        this.remarque = remarque;
    }

    
    @Column(name="IDUSER", precision=22, scale=0)
    public BigDecimal getIduser() {
        return this.iduser;
    }
    
    public void setIduser(BigDecimal iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="COLUMN1", length=20)
    public String getColumn1() {
        return this.column1;
    }
    
    public void setColumn1(String column1) {
        this.column1 = column1;
    }

/*@OneToMany(fetch=FetchType.LAZY, mappedBy="formationbeneficiaire")
    public Set<Formationbeneficaire> getFormationbeneficaires() {
        return this.formationbeneficaires;
    }
    
    public void setFormationbeneficaires(Set<Formationbeneficaire> formationbeneficaires) {
        this.formationbeneficaires = formationbeneficaires;
    }*/

@OneToMany(fetch=FetchType.LAZY, mappedBy="beneficiaire")
    public Set<Beneficiairedon> getBeneficiairedons() {
        return this.beneficiairedons;
    }
    
    public void setBeneficiairedons(Set<Beneficiairedon> beneficiairedons) {
        this.beneficiairedons = beneficiairedons;
    }

/*@OneToMany(fetch=FetchType.LAZY, mappedBy="beneficiaire")
    public Set<Beneficiairecooperative> getBeneficiairecooperatives() {
        return this.beneficiairecooperatives;
    }
    
    public void setBeneficiairecooperatives(Set<Beneficiairecooperative> beneficiairecooperatives) {
        this.beneficiairecooperatives = beneficiairecooperatives;
    }*/




}


