package com.pej.domains;
// Generated 30 oct. 2016 22:13:12 by Hibernate Tools 5.2.0.Beta1



import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import org.hibernate.annotations.Proxy;
import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Candidat generated by hbm2java
 */
@Entity
@Table(name="CANDIDAT"
)
@Proxy(lazy=false)
//@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@JsonIgnoreProperties(value = { "handler", "hibernateLazyInitializer" })
public class Candidat  implements java.io.Serializable {


     /**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer idcandidat;
     private Statutcandidat statutcandidat;
     private Agent agent;
     private String nom;
     private String prenom;
     @DateTimeFormat(pattern = "dd/MM/yyyy")
     private Date datenaissance;
     private String docidentite;
     private String niveau;
     private String diplome;
     private String codearrondissement;
     private String userlogin;
     @DateTimeFormat(pattern = "dd/MM/yyyy")
     private Date datecreation;
     private String refdocidentite;
     private String telprincipal;
     private String telalternatif;
     private Integer age;
     private String sexe;
     private String situationmatrimoniale;
     private String parentechefmenage;
     private Integer nbpersonnemenage;
     private String menagebeneficiaire;
     private String scolarise;
     private String dernierniveauetude;
     private String lecture;
     private String ecriture;
     private String qualificationpersonelle;
     private String worklastmonth;
     private String recherchetravail;
     private String motifnonrecherche;
     private String activiteactuelle;
     private String asoncompte;
     private Integer nbmoistravail;
     private Integer nbjoursmoyen;
     private Integer nbheuremoyen;
     private String revenumoyen;
     private String domainesouhait;
     private String travailgroupe;
     private String numcarteagratter;
     @JsonIgnore
     private Quartier quartier;
     private String commune;
     private String departement;
     @DateTimeFormat(pattern = "dd/MM/yyyy")
     private Date dateenregistrement;
     private String dateenregistrementStr;
     private String numeroagent;
     private String numerofiche;
     private String languesparlees;
     private String precisionactivite;
     private String precisionactivitesouhaiter;
     private int niveauvalidation;
     private String nompere;
 	 private String nommere;
 	 private String photolink;

 	 //New property
 	 private String deviceid;
	 private String agentenregistreur;
	 private String enqueteur;
	 private String localdepartement;
	 private String localcommune;
	 private String arrondissement;//non crée
	 private String village;
	 private String nourrison;
	 private String documentidentite;
	 private String autredocidentite;
	 private String beneficiairepsdcc;
	 private String liencm;
	 private String  autreniveauetude;
	 private String niveaualphabetfr;
	 private String niveaualphabetlocal;
	 private String formationentrepreunariat;
	 private String autrerecherchetravail;
	 private String activiteprincipale;
	 private String employeur;
	 private String codebarre;
	 private String numeroserie;
	 private String numerocandidat;
	 private String nomradio;
	 private String commentaire;
	 private String agentautre;
	 private String autreslanguesparlees;
	 private String autrequalifpersonelle;
	 private String consentement;
	 private String devicephonenum;
	 private Timestamp starttime;
	 private Timestamp endtime;
	 private String lieupassagetemps;
	 private String nomautoritelocale;
	 private String titreautoritelocale;
	 private String ilot;
	 private String rue;
	 private String parcelnomproprio;
	 private String pointrepere1;
	 private String pointrepere2;
	 private Timestamp submissiondate;
	 private String smid;
	 private String subscriberid;
	 private String key;
	 private String metainstancename;
     private Set<Formationbeneficaire> formationbeneficaires = new HashSet<Formationbeneficaire>(0);
     @JsonIgnore
     private Set<Fichefinancement> fichefinancements = new HashSet<Fichefinancement>(0);
     @JsonIgnore
     private Set<Entreprise> entreprises = new HashSet<Entreprise>(0);
    public Candidat() {
    }


    public Candidat(Integer idcandidat) {
        this.idcandidat = idcandidat;
    }
    public Candidat(Integer idcandidat, Agent agent, String nom, String prenom, Date datenaissance, String docidentite, String niveau, String diplome, String codearrondissement, String userlogin, Date datecreation, String refdocidentite, String telprincipal, String telalternatif, Integer age, String sexe, String situationmatrimoniale, String parentechefmenage, Integer nbpersonnemenage, String menagebeneficiaire, String scolarise, String dernierniveauetude, String niveaualphabetisation, String qualificationpersonelle, String worklastmonth, String recherchetravail, String motifnonrecherche, String activiteactuelle, String asoncompte, Integer nbmoistravail, Integer nbjoursmoyen, Integer nbheuremoyen, String revenumoyen, String domainesouhait, String travailgroupe, String numcarteagratter, Quartier quartier, String commune, String departement, Date dateenregistrement, String numeroagent, String numerofiche, Set<Beneficiaire> beneficiaires) {
       this.idcandidat = idcandidat;
       this.agent = agent;
       this.nom = nom;
       this.prenom = prenom;
       this.datenaissance = datenaissance;
       this.docidentite = docidentite;
       this.niveau = niveau;
       this.diplome = diplome;
       this.codearrondissement = codearrondissement;
       this.userlogin = userlogin;
       this.datecreation = datecreation;
       this.refdocidentite = refdocidentite;
       this.telprincipal = telprincipal;
       this.telalternatif = telalternatif;
       this.age = age;
       this.sexe = sexe;
       this.situationmatrimoniale = situationmatrimoniale;
       this.parentechefmenage = parentechefmenage;
       this.nbpersonnemenage = nbpersonnemenage;
       this.menagebeneficiaire = menagebeneficiaire;
       this.scolarise = scolarise;
       this.dernierniveauetude = dernierniveauetude;
       this.lecture = lecture;
       this.qualificationpersonelle = qualificationpersonelle;
       this.worklastmonth = worklastmonth;
       this.recherchetravail = recherchetravail;
       this.motifnonrecherche = motifnonrecherche;
       this.activiteactuelle = activiteactuelle;
       this.asoncompte = asoncompte;
       this.nbmoistravail = nbmoistravail;
       this.nbjoursmoyen = nbjoursmoyen;
       this.nbheuremoyen = nbheuremoyen;
       this.revenumoyen = revenumoyen;
       this.domainesouhait = domainesouhait;
       this.travailgroupe = travailgroupe;
       this.numcarteagratter = numcarteagratter;
       this.quartier = quartier;
       this.commune = commune;
       this.departement = departement;
       this.dateenregistrement = dateenregistrement;
       this.numeroagent = numeroagent;
       this.numerofiche = numerofiche;

    }

	@Id
	@GeneratedValue(generator = "SEQ_IDCANDIDAT", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "SEQ_IDCANDIDAT", sequenceName = "SEQ_IDCANDIDAT",allocationSize=1)
	@Column(name="IDCANDIDAT", unique=true, nullable=false, precision=22, scale=0)
    public Integer getIdcandidat() {
        return this.idcandidat;
    }

    public void setIdcandidat(Integer idcandidat) {
        this.idcandidat = idcandidat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDAGENT")
    public Agent getAgent() {
        return this.agent;
    }

    public void setAgent(Agent agent) {
        this.agent = agent;
    }


    @Column(name="NOM", length=1024)
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }


    @Column(name="PRENOM", length=1024)
    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATENAISSANCE", length=1024)
    public Date getDatenaissance() {
        return this.datenaissance;
    }

    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }


    @Column(name="DOCIDENTITE", length=1024)
    public String getDocidentite() {
        return this.docidentite;
    }

    public void setDocidentite(String docidentite) {
        this.docidentite = docidentite;
    }


    @Column(name="NIVEAU", length=1024)
    public String getNiveau() {
        return this.niveau;
    }

    public void setNiveau(String niveau) {
        this.niveau = niveau;
    }


    @Column(name="DIPLOME", length=1024)
    public String getDiplome() {
        return this.diplome;
    }

    public void setDiplome(String diplome) {
        this.diplome = diplome;
    }


    @Column(name="CODEARRONDISSEMENT", length=1024)
    public String getCodearrondissement() {
        return this.codearrondissement;
    }

    public void setCodearrondissement(String codearrondissement) {
        this.codearrondissement = codearrondissement;
    }


    @Column(name="USERLOGIN", length=1024)
    public String getUserlogin() {
        return this.userlogin;
    }

    public void setUserlogin(String userlogin) {
        this.userlogin = userlogin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATECREATION", length=7)
    public Date getDatecreation() {
        return this.datecreation;
    }

    public void setDatecreation(Date datecreation) {
        this.datecreation = datecreation;
    }


    @Column(name="REFDOCIDENTITE", length=1024)
    public String getRefdocidentite() {
        return this.refdocidentite;
    }

    public void setRefdocidentite(String refdocidentite) {
        this.refdocidentite = refdocidentite;
    }


    @Column(name="TELPRINCIPAL", length=1024)
    public String getTelprincipal() {
        return this.telprincipal;
    }

    public void setTelprincipal(String telprincipal) {
        this.telprincipal = telprincipal;
    }


    @Column(name="TELALTERNATIF", length=1024)
    public String getTelalternatif() {
        return this.telalternatif;
    }

    public void setTelalternatif(String telalternatif) {
        this.telalternatif = telalternatif;
    }


    @Column(name="AGE", precision=22, scale=0)
    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }


    @Column(name="SEXE", length=1024)
    public String getSexe() {
        return this.sexe;
    }

    public void setSexe(String sexe) {
        this.sexe = sexe;
    }


    @Column(name="SITUATIONMATRIMONIALE", length=1024)
    public String getSituationmatrimoniale() {
        return this.situationmatrimoniale;
    }

    public void setSituationmatrimoniale(String situationmatrimoniale) {
        this.situationmatrimoniale = situationmatrimoniale;
    }


    @Column(name="PARENTECHEFMENAGE", length=128)
    public String getParentechefmenage() {
        return this.parentechefmenage;
    }

    public void setParentechefmenage(String parentechefmenage) {
        this.parentechefmenage = parentechefmenage;
    }


    @Column(name="NBPERSONNEMENAGE", precision=22, scale=0)
    public Integer getNbpersonnemenage() {
        return this.nbpersonnemenage;
    }

    public void setNbpersonnemenage(Integer nbpersonnemenage) {
        this.nbpersonnemenage = nbpersonnemenage;
    }


    @Column(name="MENAGEBENEFICIAIRE")
    public String getMenagebeneficiaire() {
        return this.menagebeneficiaire;
    }

    public void setMenagebeneficiaire(String menagebeneficiaire) {
        this.menagebeneficiaire = menagebeneficiaire;
    }


    @Column(name="SCOLARISE", precision=22, scale=0)
    public String getScolarise() {
        return this.scolarise;
    }

    public void setScolarise(String scolarise) {
        this.scolarise = scolarise;
    }


    @Column(name="DERNIERNIVEAUETUDE", length=128)
    public String getDernierniveauetude() {
        return this.dernierniveauetude;
    }

    public void setDernierniveauetude(String dernierniveauetude) {
        this.dernierniveauetude = dernierniveauetude;
    }


    @Column(name="LECTURE", precision=22, scale=0)
    public String getLecture() {
        return this.lecture;
    }

    public void setLecture(String lecture) {
        this.lecture =lecture;
    }

    @Column(name="ECRITURE", precision=22, scale=0)
    public String getEcriture() {
        return this.ecriture;
    }

    public void setEcriture(String ecriture) {
        this.ecriture = ecriture;
    }

    @Column(name="QUALIFICATIONPERSONELLE", length=128)
    public String getQualificationpersonelle() {
        return this.qualificationpersonelle;
    }

    public void setQualificationpersonelle(String qualificationpersonelle) {
        this.qualificationpersonelle = qualificationpersonelle;
    }


    @Column(name="WORKLASTMONTH")
    public String getWorklastmonth() {
        return this.worklastmonth;
    }

    public void setWorklastmonth(String worklastmonth) {
        this.worklastmonth = worklastmonth;
    }


    @Column(name="RECHERCHETRAVAIL")
    public String getRecherchetravail() {
        return this.recherchetravail;
    }

    public void setRecherchetravail(String recherchetravail) {
        this.recherchetravail = recherchetravail;
    }


    @Column(name="MOTIFNONRECHERCHE")
    public String getMotifnonrecherche() {
        return this.motifnonrecherche;
    }

    public void setMotifnonrecherche(String motifnonrecherche) {
        this.motifnonrecherche = motifnonrecherche;
    }


    @Column(name="ACTIVITEACTUELLE")
    public String getActiviteactuelle() {
        return this.activiteactuelle;
    }

    public void setActiviteactuelle(String activiteactuelle) {
        this.activiteactuelle = activiteactuelle;
    }


    @Column(name="ASONCOMPTE", length=128)
    public String getAsoncompte() {
        return this.asoncompte;
    }

    public void setAsoncompte(String asoncompte) {
        this.asoncompte = asoncompte;
    }


    @Column(name="NBMOISTRAVAIL", precision=22, scale=0)
    public Integer getNbmoistravail() {
        return this.nbmoistravail;
    }

    public void setNbmoistravail(Integer nbmoistravail) {
        this.nbmoistravail = nbmoistravail;
    }


    @Column(name="NBJOURSMOYEN", precision=22, scale=0)
    public Integer getNbjoursmoyen() {
        return this.nbjoursmoyen;
    }

    public void setNbjoursmoyen(Integer nbjoursmoyen) {
        this.nbjoursmoyen = nbjoursmoyen;
    }


    @Column(name="NBHEUREMOYEN", precision=22, scale=0)
    public Integer getNbheuremoyen() {
        return this.nbheuremoyen;
    }

    public void setNbheuremoyen(Integer nbheuremoyen) {
        this.nbheuremoyen = nbheuremoyen;
    }


    @Column(name="REVENUMOYEN", precision=22, scale=0)
    public String getRevenumoyen() {
        return this.revenumoyen;
    }

    public void setRevenumoyen(String revenumoyen) {
        this.revenumoyen = revenumoyen;
    }


    @Column(name="DOMAINESOUHAIT")
    public String getDomainesouhait() {
        return this.domainesouhait;
    }

    public void setDomainesouhait(String domainesouhait) {
        this.domainesouhait = domainesouhait;
    }


    @Column(name="TRAVAILGROUPE")
    public String getTravailgroupe() {
        return this.travailgroupe;
    }

    public void setTravailgroupe(String travailgroupe) {
        this.travailgroupe = travailgroupe;
    }


    @Column(name="NUMCARTEAGRATTER", length=20)
    public String getNumcarteagratter() {
        return this.numcarteagratter;
    }

    public void setNumcarteagratter(String numcarteagratter) {
        this.numcarteagratter = numcarteagratter;
    }




    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDQUARTIER")
    public Quartier getQuartier() {
        return this.quartier;
    }

    public void setQuartier(Quartier quartier) {
        this.quartier = quartier;
    }


    @Column(name="COMMUNE", length=128)
    public String getCommune() {
        return this.commune;
    }

    public void setCommune(String commune) {
        this.commune = commune;
    }


    @Column(name="DEPARTEMENT", length=1024)
    public String getDepartement() {
        return this.departement;
    }

    public void setDepartement(String departement) {
        this.departement = departement;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEENREGISTREMENT", length=7)
    public Date getDateenregistrement() {
        return this.dateenregistrement;
    }

    public void setDateenregistrement(Date dateenregistrement) {
        this.dateenregistrement = dateenregistrement;
    }


    @Column(name="NUMEROAGENT", length=1024)
    public String getNumeroagent() {
        return this.numeroagent;
    }

    public void setNumeroagent(String numeroagent) {
        this.numeroagent = numeroagent;
    }


    @Column(name="NUMEROFICHE", length=1024)
    public String getNumerofiche() {
        return this.numerofiche;
    }

    public void setNumerofiche(String numerofiche) {
        this.numerofiche = numerofiche;
    }


    @Column(name="LANGUESPARLEES", length=1024)
    public String getLanguesparlees() {
        return this.languesparlees;
    }

    public void setLanguesparlees(String languesparlees) {
        this.nom = languesparlees;
    }
    @Column(name = "NOMMERE")
	public String getNommere() {
		return this.nommere;
	}

	public void setNommere(String nommere) {
		this.nommere = nommere;
	}

	 @Column(name = "NOMPERE")
	public String getNompere() {
		return this.nompere;
	}

	public void setNompere(String nompere) {
		this.nompere = nompere;
	}

	@Column(name = "PHOTOLINK", length = 100)
	public String getPhotolink() {
		return this.photolink;
	}

	public void setPhotolink(String photolink) {
		this.photolink = photolink;
	}
    @Column(name="PRECISIONACTIVITE", length=1024)
    public String getPrecisionactivite() {
        return this.precisionactivite;
    }

    public void setPrecisionactivite(String precisionactivite) {
        this.precisionactivite = precisionactivite;
    }
    @Column(name="PRECISIONACTIVITESOUHAITER", length=1024)
    public String getPrecisionactivitesouhaiter() {
        return this.precisionactivitesouhaiter;
    }

    public void setPrecisionactivitesouhaiter(String precisionactivitesouhaiter) {
        this.precisionactivitesouhaiter = precisionactivitesouhaiter;
    }

    @ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDSTATUT")
	public Statutcandidat getStatutcandidat() {
		return this.statutcandidat;
	}

	public void setStatutcandidat(Statutcandidat statutcandidat) {
		this.statutcandidat = statutcandidat;
	}



	@Column(name="NIVEAUVALIDATION", precision=22, scale=0)
	public int getNiveauvalidation() {
		return niveauvalidation;
	}


	public void setNiveauvalidation(int niveauvalidation) {
		this.niveauvalidation = niveauvalidation;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="formation")
    public Set<Formationbeneficaire> getFormationbeneficaires() {
        return this.formationbeneficaires;
    }

    public void setFormationbeneficaires(Set<Formationbeneficaire> formationbeneficaires) {
        this.formationbeneficaires = formationbeneficaires;
    }
    @OneToMany(fetch=FetchType.LAZY, mappedBy="candidat")
    public Set<Fichefinancement> getFichefinancements() {
        return this.fichefinancements;
    }

    public void setFichefinancements(Set<Fichefinancement> fichefinancements) {
        this.fichefinancements = fichefinancements;
    }
    @OneToMany(fetch=FetchType.LAZY, mappedBy="candidat")
    public Set<Entreprise> getEntreprises() {
        return this.entreprises;
    }

    public void setEntreprises(Set<Entreprise> entreprises) {
        this.entreprises = entreprises;
    }



	@Override
	public String toString() {
		return "Candidat [idcandidat=" + idcandidat + ", agent=" + agent + ", nom=" + nom + ", prenom=" + prenom
				+ ", datenaissance=" + datenaissance + ", docidentite=" + docidentite + ", niveau=" + niveau
				+ ", diplome=" + diplome + ", codearrondissement=" + codearrondissement + ", userlogin=" + userlogin
				+ ", datecreation=" + datecreation + ", refdocidentite=" + refdocidentite + ", telprincipal="
				+ telprincipal + ", telalternatif=" + telalternatif + ", age=" + age + ", sexe=" + sexe
				+ ", situationmatrimoniale=" + situationmatrimoniale + ", parentechefmenage=" + parentechefmenage
				+ ", nbpersonnemenage=" + nbpersonnemenage + ", menagebeneficiaire=" + menagebeneficiaire
				+ ", scolarise=" + scolarise + ", dernierniveauetude=" + dernierniveauetude + ", lecture=" + lecture
				+ ", ecriture=" + ecriture + ", qualificationpersonelle=" + qualificationpersonelle + ", worklastmonth="
				+ worklastmonth + ", recherchetravail=" + recherchetravail + ", motifnonrecherche=" + motifnonrecherche
				+ ", activiteactuelle=" + activiteactuelle + ", asoncompte=" + asoncompte + ", nbmoistravail="
				+ nbmoistravail + ", nbjoursmoyen=" + nbjoursmoyen + ", nbheuremoyen=" + nbheuremoyen + ", revenumoyen="
				+ revenumoyen + ", domainesouhait=" + domainesouhait + ", travailgroupe=" + travailgroupe
				+ ", numcarteagratter=" + numcarteagratter  + ", quartier=" + quartier
				+ ", commune=" + commune + ", departement=" + departement + ", dateenregistrement=" + dateenregistrement
				+ ", numeroagent=" + numeroagent + ", numerofiche=" + numerofiche + ", languesparlees=" + languesparlees
				+ ", precisionactivite=" + precisionactivite + ", precisionactivitesouhaiter="
				+ precisionactivitesouhaiter + ", beneficiaires="  + "]";
	}

	@Column(name="deviceid", length=1024)
	public String getDeviceid() {
		return deviceid;
	}


	public void setDeviceid(String deviceid) {
		this.deviceid = deviceid;
	}

	@Column(name="agentenregistreur", length=1024)
	public String getAgentenregistreur() {
		return agentenregistreur;
	}


	public void setAgentenregistreur(String agentenregistreur) {
		this.agentenregistreur = agentenregistreur;
	}

	@Column(name="enqueteur", length=1024)
	public String getEnqueteur() {
		return enqueteur;
	}


	public void setEnqueteur(String enqueteur) {
		this.enqueteur = enqueteur;
	}

	@Column(name="localdepartement", length=1024)
	public String getLocaldepartement() {
		return localdepartement;
	}


	public void setLocaldepartement(String localdepartement) {
		this.localdepartement = localdepartement;
	}

	@Column(name="localcommune", length=1024)
	public String getLocalcommune() {
		return localcommune;
	}


	public void setLocalcommune(String localcommune) {
		this.localcommune = localcommune;
	}

	@Column(name="arrondissement", length=1024)
	public String getArrondissement() {
		return arrondissement;
	}


	public void setArrondissement(String arrondissement) {
		this.arrondissement = arrondissement;
	}

	@Column(name="village", length=1024)
	public String getVillage() {
		return village;
	}


	public void setVillage(String village) {
		this.village = village;
	}

	@Column(name="nourrison", length=1024)
	public String getNourrison() {
		return nourrison;
	}


	public void setNourrison(String nourrison) {
		this.nourrison = nourrison;
	}

	@Column(name="documentidentite", length=1024)
	public String getDocumentidentite() {
		return documentidentite;
	}


	public void setDocumentidentite(String documentidentite) {
		this.documentidentite = documentidentite;
	}

	@Column(name="autredocidentite", length=1024)
	public String getAutredocidentite() {
		return autredocidentite;
	}


	public void setAutredocidentite(String autredocidentite) {
		this.autredocidentite = autredocidentite;
	}

	@Column(name="beneficiairepsdcc", length=1024)
	public String getBeneficiairepsdcc() {
		return beneficiairepsdcc;
	}


	public void setBeneficiairepsdcc(String beneficiairepsdcc) {
		this.beneficiairepsdcc = beneficiairepsdcc;
	}

	@Column(name="liencm", length=1024)
	public String getLiencm() {
		return liencm;
	}


	public void setLiencm(String liencm) {
		this.liencm = liencm;
	}

	@Column(name="autreniveauetude", length=1024)
	public String getAutreniveauetude() {
		return autreniveauetude;
	}


	public void setAutreniveauetude(String autreniveauetude) {
		this.autreniveauetude = autreniveauetude;
	}

	@Column(name="niveaualphabetfr", length=1024)
	public String getNiveaualphabetfr() {
		return niveaualphabetfr;
	}


	public void setNiveaualphabetfr(String niveaualphabetfr) {
		this.niveaualphabetfr = niveaualphabetfr;
	}

	@Column(name="niveaualphabetlocal", length=1024)
	public String getNiveaualphabetlocal() {
		return niveaualphabetlocal;
	}


	public void setNiveaualphabetlocal(String niveaualphabetlocal) {
		this.niveaualphabetlocal = niveaualphabetlocal;
	}

	@Column(name="formationentrepreunariat", length=1024)
	public String getFormationentrepreunariat() {
		return formationentrepreunariat;
	}


	public void setFormationentrepreunariat(String formationentrepreunariat) {
		this.formationentrepreunariat = formationentrepreunariat;
	}

	@Column(name="autrerecherchetravail", length=1024)
	public String getAutrerecherchetravail() {
		return autrerecherchetravail;
	}


	public void setAutrerecherchetravail(String autrerecherchetravail) {
		this.autrerecherchetravail = autrerecherchetravail;
	}

	@Column(name="activiteprincipale", length=1024)
	public String getActiviteprincipale() {
		return activiteprincipale;
	}


	public void setActiviteprincipale(String activiteprincipale) {
		this.activiteprincipale = activiteprincipale;
	}

	@Column(name="employeur", length=1024)
	public String getEmployeur() {
		return employeur;
	}


	public void setEmployeur(String employeur) {
		this.employeur = employeur;
	}

	@Column(name="codebarre", length=1024)
	public String getCodebarre() {
		return codebarre;
	}


	public void setCodebarre(String codebarre) {
		this.codebarre = codebarre;
	}

	@Column(name="numeroserie", length=1024)
	public String getNumeroserie() {
		return numeroserie;
	}


	public void setNumeroserie(String numeroserie) {
		this.numeroserie = numeroserie;
	}

	@Column(name="numerocandidat", length=1024)
	public String getNumerocandidat() {
		return numerocandidat;
	}


	public void setNumerocandidat(String numerocandidat) {
		this.numerocandidat = numerocandidat;
	}

	@Column(name="nomradio", length=1024)
	public String getNomradio() {
		return nomradio;
	}


	public void setNomradio(String nomradio) {
		this.nomradio = nomradio;
	}

	@Column(name="commentaire", length=1024)
	public String getCommentaire() {
		return commentaire;
	}


	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}


	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Column(name="agentautre", length=1024)
	public String getAgentautre() {
		return agentautre;
	}


	public void setAgentautre(String agentautre) {
		this.agentautre = agentautre;
	}

	@Column(name="autreslanguesparlees", length=1024)
	public String getAutreslanguesparlees() {
		return autreslanguesparlees;
	}


	public void setAutreslanguesparlees(String autreslanguesparlees) {
		this.autreslanguesparlees = autreslanguesparlees;
	}

	@Column(name="autrequalifpersonelle", length=1024)
	public String getAutrequalifpersonelle() {
		return autrequalifpersonelle;
	}


	public void setAutrequalifpersonelle(String autrequalifpersonelle) {
		this.autrequalifpersonelle = autrequalifpersonelle;
	}

	@Column(name="consentement", length=1024)
	public String getConsentement() {
		return consentement;
	}


	public void setConsentement(String consentement) {
		this.consentement = consentement;
	}

	@Column(name="devicephonenum", length=1024)
	public String getDevicephonenum() {
		return devicephonenum;
	}


	public void setDevicephonenum(String devicephonenum) {
		this.devicephonenum = devicephonenum;
	}

	@Column(name="starttime")
	public Timestamp getStarttime() {
		return starttime;
	}


	public void setStarttime(Timestamp starttime) {
		this.starttime = starttime;
	}

	@Column(name="endtime")
	public Timestamp getEndtime() {
		return endtime;
	}


	public void setEndtime(Timestamp endtime) {
		this.endtime = endtime;
	}

	@Column(name="lieu_passage_temps", length=1024)
	public String getLieupassagetemps() {
		return lieupassagetemps;
	}


	public void setLieupassagetemps(String lieupassagetemps) {
		this.lieupassagetemps = lieupassagetemps;
	}

	@Column(name="nom_autorite_locale", length=1024)
	public String getNomautoritelocale() {
		return nomautoritelocale;
	}


	public void setNomautoritelocale(String nomautoritelocale) {
		this.nomautoritelocale = nomautoritelocale;
	}

	@Column(name="titre_autorite_locale", length=1024)
	public String getTitreautoritelocale() {
		return titreautoritelocale;
	}


	public void setTitreautoritelocale(String titreautoritelocale) {
		this.titreautoritelocale = titreautoritelocale;
	}

	@Column(name="ilot", length=1024)
	public String getIlot() {
		return ilot;
	}


	public void setIlot(String ilot) {
		this.ilot = ilot;
	}

	@Column(name="rue", length=1024)
	public String getRue() {
		return rue;
	}


	public void setRue(String rue) {
		this.rue = rue;
	}

	@Column(name="parcel_nom_proprio", length=1024)
	public String getParcelnomproprio() {
		return parcelnomproprio;
	}


	public void setParcelnomproprio(String parcelnomproprio) {
		this.parcelnomproprio = parcelnomproprio;
	}

	@Column(name="point_repere1", length=1024)
	public String getPointrepere1() {
		return pointrepere1;
	}


	public void setPointrepere1(String pointrepere1) {
		this.pointrepere1 = pointrepere1;
	}

	@Column(name="point_repere2", length=1024)
	public String getPointrepere2() {
		return pointrepere2;
	}


	public void setPointrepere2(String pointrepere2) {
		this.pointrepere2 = pointrepere2;
	}

	@Column(name="submissiondate")
	public Timestamp getSubmissiondate() {
		return submissiondate;
	}


	public void setSubmissiondate(Timestamp submissiondate) {
		this.submissiondate = submissiondate;
	}

	@Column(name="smid", length=1024)
	public String getSmid() {
		return smid;
	}


	public void setSmid(String smid) {
		this.smid = smid;
	}

	@Column(name="subscriberid", length=1024)
	public String getSubscriberid() {
		return subscriberid;
	}


	public void setSubscriberid(String subscriberid) {
		this.subscriberid = subscriberid;
	}

	@Column(name="key", length=1024)
	public String getKey() {
		return key;
	}


	public void setKey(String key) {
		this.key = key;
	}

	@Column(name="meta_instancename", length=1024)
	public String getMetainstancename() {
		return metainstancename;
	}


	public void setMetainstancename(String metainstancename) {
		this.metainstancename = metainstancename;
	}

    @Column(name="dateenregistrementStr", length=1024)
    public String getDateenregistrementStr() {
        return dateenregistrementStr;
    }

    public void setDateenregistrementStr(String dateenregistrementStr) {
        this.dateenregistrementStr = dateenregistrementStr;
    }

    @Transient
	public String getIdentite(){
        return this.nom + " "+ this.prenom;
    }




}


