package com.pej.domains;
// Generated 6 oct. 2016 04:12:45 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.*;


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Commune generated by hbm2java
 */
@Entity
@Table(name = "COMMUNE", schema = "ADMINPEJ")
public class Commune implements java.io.Serializable {

	private String codecommune;
	private Departement departement;
	private String libcommune;
	private String description;
	private Set<Arrondissement> arrondissements = new HashSet<Arrondissement>(0);

	public Commune() {
	}

	public Commune(String codecommune) {
		this.codecommune = codecommune;
	}

	public Commune(String codecommune, Departement departement, String libcommune, String descriptioin,
			Set<Arrondissement> arrondissements) {
		this.codecommune = codecommune;
		this.departement = departement;
		this.libcommune = libcommune;
		this.description = descriptioin;
		this.arrondissements = arrondissements;
	}

	@Id
	@GeneratedValue
	@Column(name = "CODECOMMUNE", unique = true, nullable = false, length = 20)
	public String getCodecommune() {
		return this.codecommune;
	}

	public void setCodecommune(String codecommune) {
		this.codecommune = codecommune;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEDEPARTEMENT")
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@Column(name = "LIBCOMMUNE", length = 50)
	public String getLibcommune() {
		return this.libcommune;
	}

	public void setLibcommune(String libcommune) {
		this.libcommune = libcommune;
	}

	@Column(name = "DESCRIPTION", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String descriptioin) {
		this.description = descriptioin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commune")
	public Set<Arrondissement> getArrondissements() {
		return this.arrondissements;
	}

	public void setArrondissements(Set<Arrondissement> arrondissements) {
		this.arrondissements = arrondissements;
	}

}
