package com.pej.domains;
// Generated 30 oct. 2016 22:13:12 by Hibernate Tools 5.2.0.Beta1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Cooperative generated by hbm2java
 */
@Entity
@Table(name="COOPERATIVE"
)
public class Cooperative  implements java.io.Serializable {


     private Integer idgroupe;
     private String libgroupe;
     private String description;
     private Date datecreation;
     private String userlogin;
     private String type;
     private Integer nombre;
     @JsonIgnore
     private Commune commune;
     @JsonIgnore
     private  Lot lot;
     private Set<Beneficiairecooperative> beneficiairecooperatives = new HashSet<Beneficiairecooperative>(0);
     private Set<Formationcooperative> formationcooperatives = new HashSet<Formationcooperative>(0);
    public Cooperative() {
    }

	
    public Cooperative(Integer idgroupe) {
        this.idgroupe = idgroupe;
    }
    public Cooperative(Integer idgroupe, String libgroupe, String description, Date datecreation, String userlogin, Set<Beneficiairecooperative> beneficiairecooperatives) {
       this.idgroupe = idgroupe;
       this.libgroupe = libgroupe;
       this.description = description;
       this.datecreation = datecreation;
       this.userlogin = userlogin;
       this.beneficiairecooperatives = beneficiairecooperatives;
    }
   
    @Id 
    @GeneratedValue(generator = "SEQ_IDGROUPE", strategy = GenerationType.SEQUENCE)
  	@SequenceGenerator(name = "SEQ_IDGROUPE", sequenceName = "SEQ_IDGROUPE",allocationSize=1)
    @Column(name="IDGROUPE", unique=true, nullable=false, precision=22, scale=0)
    public Integer getIdgroupe() {
        return this.idgroupe;
    }
    
    public void setIdgroupe(Integer idgroupe) {
        this.idgroupe = idgroupe;
    }

    
    @Column(name="LIBGROUPE", length=20)
    public String getLibgroupe() {
        return this.libgroupe;
    }
    
    public void setLibgroupe(String libgroupe) {
        this.libgroupe = libgroupe;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATECREATION", length=7)
    public Date getDatecreation() {
        return this.datecreation;
    }
    
    public void setDatecreation(Date datecreation) {
        this.datecreation = datecreation;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODECOMMUNE")
    public Commune getCommune() {
        return this.commune;
    }
    
    public void setCommune(Commune commune) {
        this.commune = commune;
    }
    
    @Column(name="USERLOGIN", length=1024)
    public String getUserlogin() {
        return this.userlogin;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    @Column(name="TYPE", length=1024)
    public String getType() {
        return this.type;
    }
    
    
    @Column(name="NOMBRE", nullable=true, precision=22, scale=0)
    public Integer getNombre() {
		return nombre;
	}


	public void setNombre(Integer nombre) {
		this.nombre = nombre;
	}


	public void setUserlogin(String userlogin) {
        this.userlogin = userlogin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cooperative")
    public Set<Beneficiairecooperative> getBeneficiairecooperatives() {
        return this.beneficiairecooperatives;
    }
    
    public void setBeneficiairecooperatives(Set<Beneficiairecooperative> beneficiairecooperatives) {
        this.beneficiairecooperatives = beneficiairecooperatives;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDLOT")
	public Lot getLot() {
		return lot;
	}


	public void setLot(Lot lot) {
		this.lot = lot;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cooperative")
	public Set<Formationcooperative> getFormationcooperatives() {
		return this.formationcooperatives;
	}

	public void setFormationcooperatives(Set<Formationcooperative> formationcooperatives) {
		this.formationcooperatives = formationcooperatives;
	}
	@Override
	public String toString() {
        return libgroupe;

    }



}


