package com.pej.domains;
// Generated 6 oct. 2016 04:12:45 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name = "DEPARTEMENT", schema = "ADMINPEJ")
public class Departement implements java.io.Serializable {

	
	private Integer codedepartement;
	@NotNull
	@Size(min=3, max=50)
	private String libdeparteement;
	private String description;
	private Set<Commune> communes = new HashSet<Commune>(0);

	public Departement() {
	}

	public Departement(Integer codedepartement) {
		this.codedepartement = codedepartement;
	}

	public Departement(Integer codedepartement, String libdeparteement, String description, Set<Commune> communes) {
		this.codedepartement = codedepartement;
		this.libdeparteement = libdeparteement;
		this.description = description;
		this.communes = communes;
	}

	@Id
	@GeneratedValue(generator = "SEC_DEPARTEMENT", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "SEC_DEPARTEMENT", sequenceName = "SEQ_IDDEPARTEMENT",allocationSize=1)
	@Column(name = "CODEDEPARTEMENT", unique = true, nullable = false, length = 20)
	public Integer getCodedepartement() {
		return this.codedepartement;
	}

	public void setCodedepartement(Integer codedepartement) {
		this.codedepartement = codedepartement;
	}

	@Column(name = "LIBDEPARTEEMENT", length = 50)
	public String getLibdeparteement() {
		return this.libdeparteement;
	}

	public void setLibdeparteement(String libdeparteement) {
		this.libdeparteement = libdeparteement;
	}

	@Column(name = "DESCRIPTION", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departement")
	public Set<Commune> getCommunes() {
		return this.communes;
	}

	public void setCommunes(Set<Commune> communes) {
		this.communes = communes;
	}

}
