package com.pej.domains;
// Generated 15 janv. 2017 23:01:46 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Dossiers generated by hbm2java
 */
@Entity
@Table(name = "DOSSIERS")
public class Dossiers implements java.io.Serializable {

	private Integer iddossier;
	private Candidat candidat;
	private String nature;
	private String link;

	public Dossiers() {
	}

	public Dossiers(Integer iddossier) {
		this.iddossier = iddossier;
	}

	public Dossiers(Integer iddossier, Candidat candidat, String nature, String link) {
		this.iddossier = iddossier;
		this.candidat = candidat;
		this.nature = nature;
		this.link = link;
	}

	
	@Id 
  	@GeneratedValue(generator = "SEQ_IDDOSSIER", strategy = GenerationType.SEQUENCE)
  	@SequenceGenerator(name = "SEQ_IDDOSSIER", sequenceName = "SEQ_IDDOSSIER",allocationSize=1)
   	@Column(name = "IDDOSSIER", unique = true, nullable = false, length = 20)
	public Integer getIddossier() {
		return this.iddossier;
	}

	public void setIddossier(Integer iddossier) {
		this.iddossier = iddossier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCANDIDAT")
	public Candidat getCandidat() {
		return this.candidat;
	}

	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}

	@Column(name = "NATURE")
	public String getNature() {
		return this.nature;
	}

	public void setNature(String nature) {
		this.nature = nature;
	}

	@Column(name = "LINK")
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

}
