package com.pej.domains;
// Generated 7 janv. 2017 00:38:44 by Hibernate Tools 5.2.0.Beta1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Formationcooperative generated by hbm2java
 */
@Entity
@Table(name = "FORMATIONCOOPERATIVE")
public class Formationcooperative implements java.io.Serializable {

	private Integer idformationcooperative;
	private Formation formation;
	private Cooperative cooperative;
	private Date dateajout;
	private String userlogin;

	public Formationcooperative() {
	}

	public Formationcooperative(Integer idformationcooperative) {
		this.idformationcooperative = idformationcooperative;
	}

	public Formationcooperative(Integer idformationcooperative, Formation formation, Cooperative cooperative,
			Date dateajout, String userlogin) {
		this.idformationcooperative = idformationcooperative;
		this.formation = formation;
		this.cooperative = cooperative;
		this.dateajout = dateajout;
		this.userlogin = userlogin;
	}

	@Id
	@GeneratedValue(generator = "SEQ_IDFORMATIONCOOPERATIVE", strategy = GenerationType.SEQUENCE)
  	@SequenceGenerator(name = "SEQ_IDFORMATIONCOOPERATIVE", sequenceName = "SEQ_IDFORMATIONCOOPERATIVE",allocationSize=1)
	@Column(name = "IDFORMATIONCOOPERATIVE", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdformationcooperative() {
		return this.idformationcooperative;
	}

	public void setIdformationcooperative(Integer idformationcooperative) {
		this.idformationcooperative = idformationcooperative;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDFORMATION")
	public Formation getFormation() {
		return this.formation;
	}

	public void setFormation(Formation formation) {
		this.formation = formation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDGROUPE")
	public Cooperative getCooperative() {
		return this.cooperative;
	}

	public void setCooperative(Cooperative cooperative) {
		this.cooperative = cooperative;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEAJOUT", length = 7)
	public Date getDateajout() {
		return this.dateajout;
	}

	public void setDateajout(Date dateajout) {
		this.dateajout = dateajout;
	}

	@Column(name = "USERLOGIN", length = 20)
	public String getUserlogin() {
		return this.userlogin;
	}

	public void setUserlogin(String userlogin) {
		this.userlogin = userlogin;
	}

}
