package com.pej.domains;
// Generated 30 oct. 2016 22:13:12 by Hibernate Tools 5.2.0.Beta1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Formation generated by hbm2java
 */
@Entity
@Table(name="FORMATION"
    ,schema="ADMINPEJ"
)
public class Formation  implements java.io.Serializable {


     private Integer idformation;
     private Formateur formateur;
     private Date dateformation;
     private String heuredebut;
     private String heurefin;
     private String remarque;
     private Integer idgroupe;
     private String intitule;
     private Set<Formationbeneficaire> formationbeneficaires = new HashSet<Formationbeneficaire>(0);

    public Formation() {
    }

	
    public Formation(Integer idformation) {
        this.idformation = idformation;
    }
    public Formation(Integer idformation, Formateur formateur, Date dateformation, String heuredebut, String heurefin, String remarque, Integer idgroupe, Set<Formationbeneficaire> formationbeneficaires) {
       this.idformation = idformation;
       this.formateur = formateur;
       this.dateformation = dateformation;
       this.heuredebut = heuredebut;
       this.heurefin = heurefin;
       this.remarque = remarque;
       this.idgroupe = idgroupe;
       this.formationbeneficaires = formationbeneficaires;
    }
   
    @Id 
  	@GeneratedValue(generator = "SEQ_IDFORMATION", strategy = GenerationType.SEQUENCE)
  	@SequenceGenerator(name = "SEQ_IDFORMATION", sequenceName = "SEQ_IDFORMATION",allocationSize=1)
    @Column(name="IDFORMATION", unique=true, nullable=false, precision=22, scale=0)
    public Integer getIdformation() {
        return this.idformation;
    }
    
    public void setIdformation(Integer idformation) {
        this.idformation = idformation;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFORMATEUR")
    public Formateur getFormateur() {
        return this.formateur;
    }
    
    public void setFormateur(Formateur formateur) {
        this.formateur = formateur;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEFORMATION", length=7)
    public Date getDateformation() {
        return this.dateformation;
    }
    
    public void setDateformation(Date dateformation) {
        this.dateformation = dateformation;
    }

    
    @Column(name="HEUREDEBUT")
    public String getHeuredebut() {
        return this.heuredebut;
    }
    
    public void setHeuredebut(String heuredebut) {
        this.heuredebut = heuredebut;
    }

    
    @Column(name="HEUREFIN")
    public String getHeurefin() {
        return this.heurefin;
    }
    
    public void setHeurefin(String heurefin) {
        this.heurefin = heurefin;
    }

    
    @Column(name="REMARQUE")
    public String getRemarque() {
        return this.remarque;
    }
    
    public void setRemarque(String remarque) {
        this.remarque = remarque;
    }

    
    @Column(name="IDGROUPE", precision=22, scale=0)
    public Integer getIdgroupe() {
        return this.idgroupe;
    }
    
    public void setIdgroupe(Integer idgroupe) {
        this.idgroupe = idgroupe;
    }
    
    
    @Column(name="INTITULE")
    public String getIntitule() {
		return intitule;
	}


	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}


	@OneToMany(fetch=FetchType.LAZY, mappedBy="formation")
    public Set<Formationbeneficaire> getFormationbeneficaires() {
        return this.formationbeneficaires;
    }
    
    public void setFormationbeneficaires(Set<Formationbeneficaire> formationbeneficaires) {
        this.formationbeneficaires = formationbeneficaires;
    }


	@Override
	public String toString() {
		return "Formation [idformation=" + idformation + ", formateur=" + formateur + ", dateformation=" + dateformation
				+ ", heuredebut=" + heuredebut + ", heurefin=" + heurefin + ", remarque=" + remarque + ", idgroupe="
				+ idgroupe + ", intitule=" + intitule + ", formationbeneficaires=" + formationbeneficaires + "]";
	}

}


