package com.pej.domains;
// Generated 30 oct. 2016 22:13:12 by Hibernate Tools 5.2.0.Beta1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Formateur generated by hbm2java
 */
@Entity
@Table(name="FORMATEUR"
    ,schema="ADMINPEJ"
)
public class Formateur  implements java.io.Serializable {


     private Integer idformateur;
     private String nom;
     private String prenom;
     private Date datenaissance;
     private String cardid;
     private String telephone;
     private String datecreation;
     private String userlogin;
     private Set<Formation> formations = new HashSet<Formation>(0);

    public Formateur() {
    }

	
    public Formateur(Integer idformateur) {
        this.idformateur = idformateur;
    }
    public Formateur(Integer idformateur, String nom, String prenom, Date datenaissance, String cardid, String telephone, String datecreation, String userlogin, Set<Formation> formations) {
       this.idformateur = idformateur;
       this.nom = nom;
       this.prenom = prenom;
       this.datenaissance = datenaissance;
       this.cardid = cardid;
       this.telephone = telephone;
       this.datecreation = datecreation;
       this.userlogin = userlogin;
       this.formations = formations;
    }
   
     @Id 

  	@GeneratedValue(generator = "SEQ_IDFORMATEUR", strategy = GenerationType.SEQUENCE)
  	@SequenceGenerator(name = "SEQ_IDFORMATEUR", sequenceName = "SEQ_IDFORMATEUR",allocationSize=1)
    @Column(name="IDFORMATEUR", unique=true, nullable=false, precision=22, scale=0)
    public Integer getIdformateur() {
        return this.idformateur;
    }
    
    public void setIdformateur(Integer idformateur) {
        this.idformateur = idformateur;
    }

    
    @Column(name="NOM", length=20)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="PRENOM", length=20)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATENAISSANCE", length=7)
    public Date getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }

    
    @Column(name="CARDID", length=20)
    public String getCardid() {
        return this.cardid;
    }
    
    public void setCardid(String cardid) {
        this.cardid = cardid;
    }

    
    @Column(name="TELEPHONE", length=20)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="DATECREATION", length=20)
    public String getDatecreation() {
        return this.datecreation;
    }
    
    public void setDatecreation(String datecreation) {
        this.datecreation = datecreation;
    }

    
    @Column(name="USERLOGIN", length=50)
    public String getUserlogin() {
        return this.userlogin;
    }
    
    public void setUserlogin(String userlogin) {
        this.userlogin = userlogin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="formateur")
    public Set<Formation> getFormations() {
        return this.formations;
    }
    
    public void setFormations(Set<Formation> formations) {
        this.formations = formations;
    }




}


