package com.pej.domains;
// Generated 12 nov. 2016 14:53:17 by Hibernate Tools 5.2.0.Beta1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "PERMISSION")
public class Permission implements java.io.Serializable {

	private Integer idpermission;
	private String name;

	public Permission() {
	}

	public Permission(Integer idpermission) {
		this.idpermission = idpermission;
	}

	public Permission(Integer idpermission, String name) {
		this.idpermission = idpermission;
		this.name = name;
	}

	@Id
 	@GeneratedValue(generator = "SEQ_IDPERMISSION", strategy = GenerationType.SEQUENCE)
  	@SequenceGenerator(name = "SEQ_IDPERMISSION", sequenceName = "SEQ_IDPERMISSION",allocationSize=1)
	@Column(name = "IDPERMISSION", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdpermission() {
		return this.idpermission;
	}

	public void setIdpermission(Integer idpermission) {
		this.idpermission = idpermission;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
