package com.pej.domains;
// Generated 6 janv. 2017 15:44:47 by Hibernate Tools 5.2.0.Beta1


import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.util.Date;

/**
 * Presence generated by hbm2java
 */
@Entity
@Table(name = "PRESENCE")
public class Presence implements java.io.Serializable {

	private Integer idpresence;
	private Candidat candidat;
	private Formation formation;
	private String observation;
	private Integer nbpresence;
	private Date date;

	public Presence() {
	}

	@Id
    @GeneratedValue(generator = "SEQ_IDPRESENCE", strategy = GenerationType.SEQUENCE)
 	@SequenceGenerator(name = "SEQ_IDPRESENCE", sequenceName = "SEQ_IDPRESENCE",allocationSize=1)
	@Column(name = "IDPRESENCE", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdpresence() {
		return this.idpresence;
	}

	public void setIdpresence(Integer idpresence) {
		this.idpresence = idpresence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCANDIDAT")
	public Candidat getCandidat() {
		return this.candidat;
	}

	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDFORMATION")
	public Formation getFormation() {
		return this.formation;
	}

	public void setFormation(Formation formation) {
		this.formation = formation;
	}

	@Column(name = "OBSERVATION")
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}
	@Column(name = "NBPRESENCE")
	public Integer getNbpresence() {
		return nbpresence;
	}

	public void setNbpresence(Integer nbpresence) {
		this.nbpresence = nbpresence;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
