package com.pej.domains;
// Generated 6 janv. 2017 15:44:47 by Hibernate Tools 5.2.0.Beta1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Presence generated by hbm2java
 */
@Entity
@Table(name = "PRESENCE", schema = "ADMINPEJ")
public class Presence implements java.io.Serializable {

	private Integer idpresence;
	private Candidat candidat;
	private Formation formation;
	private String observation;
	private Integer nbpresence;

	public Presence() {
	}

	public Presence(Integer idpresence) {
		this.idpresence = idpresence;
	}

	public Presence(Integer idpresence, Candidat candidat, Formation formation, String observation) {
		this.idpresence = idpresence;
		this.candidat = candidat;
		this.formation = formation;
		this.observation = observation;
	}
	
	@Id
    @GeneratedValue(generator = "SEQ_IDPRESENCE", strategy = GenerationType.SEQUENCE)
 	@SequenceGenerator(name = "SEQ_IDPRESENCE", sequenceName = "SEQ_IDPRESENCE",allocationSize=1)
	@Column(name = "IDPRESENCE", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdpresence() {
		return this.idpresence;
	}

	public void setIdpresence(Integer idpresence) {
		this.idpresence = idpresence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCANDIDAT")
	public Candidat getCandidat() {
		return this.candidat;
	}

	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDFORMATION")
	public Formation getFormation() {
		return this.formation;
	}

	public void setFormation(Formation formation) {
		this.formation = formation;
	}

	@Column(name = "OBSERVATION")
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}
	@Column(name = "NBPRESENCE")
	public Integer getNbpresence() {
		return nbpresence;
	}

	public void setNbpresence(Integer nbpresence) {
		this.nbpresence = nbpresence;
	}
	
	

}
