package com.pej.domains;
// Generated 12 nov. 2016 14:53:17 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Rolespermission generated by hbm2java
 */
@Entity
@Table(name = "ROLESPERMISSION")
public class Rolespermission implements java.io.Serializable {

	private String idrolepermission;
	private Roles roles;
	private Integer idpermission;

	public Rolespermission() {
	}

	public Rolespermission(String idrolepermission) {
		this.idrolepermission = idrolepermission;
	}

	public Rolespermission(String idrolepermission, Roles roles, Integer idpermission) {
		this.idrolepermission = idrolepermission;
		this.roles = roles;
		this.idpermission = idpermission;
	}

	@Id
	@GeneratedValue(generator = "SEQ_IDROLESPERMISSION", strategy = GenerationType.SEQUENCE)
  	@SequenceGenerator(name = "SEQ_IDROLESPERMISSION", sequenceName = "SEQ_IDROLESPERMISSION",allocationSize=1)
	@Column(name = "IDROLEPERMISSION", unique = true, nullable = false, length = 20)
	public String getIdrolepermission() {
		return this.idrolepermission;
	}

	public void setIdrolepermission(String idrolepermission) {
		this.idrolepermission = idrolepermission;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDROLES")
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@Column(name = "IDPERMISSION", precision = 22, scale = 0)
	public Integer getIdpermission() {
		return this.idpermission;
	}

	public void setIdpermission(Integer idpermission) {
		this.idpermission = idpermission;
	}

}
