package com.pej.domains;
// Generated 12 nov. 2016 14:53:17 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "ROLES")
public class Roles implements java.io.Serializable {

	private Integer idrole;
	private String name;
	private Set<Rolespermission> rolespermissions = new HashSet<Rolespermission>(0);
	private Set<UsersRole> usersRoles = new HashSet<UsersRole>(0);

	public Roles() {
	}

	public Roles(Integer idrole) {
		this.idrole = idrole;
	}

	public Roles(Integer idrole, String name, Set<Rolespermission> rolespermissions, Set<UsersRole> usersRoles) {
		this.idrole = idrole;
		this.name = name;
		this.rolespermissions = rolespermissions;
		this.usersRoles = usersRoles;
	}

	@Id
 	@GeneratedValue(generator = "SEQ_IDROLES", strategy = GenerationType.SEQUENCE)
  	@SequenceGenerator(name = "SEQ_IDROLES", sequenceName = "SEQ_IDROLES",allocationSize=1)
	@Column(name = "IDROLE", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdrole() {
		return this.idrole;
	}

	public void setIdrole(Integer idrole) {
		this.idrole = idrole;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<Rolespermission> getRolespermissions() {
		return this.rolespermissions;
	}

	public void setRolespermissions(Set<Rolespermission> rolespermissions) {
		this.rolespermissions = rolespermissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<UsersRole> getUsersRoles() {
		return this.usersRoles;
	}

	public void setUsersRoles(Set<UsersRole> usersRoles) {
		this.usersRoles = usersRoles;
	}

}
