package com.pej.domains;
// Generated 14 nov. 2016 19:19:22 by Hibernate Tools 5.2.0.Beta1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Statutcandidat generated by hbm2java
 */
@Entity
@Table(name = "STATUTCANDIDAT")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Statutcandidat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String intitule;
	private Integer beneficiaireniveau;
	@JsonIgnore
	private Set<Candidat> candidats = new HashSet<Candidat>(0);

	public Statutcandidat() {
	}

	public Statutcandidat(Integer id) {
		this.id = id;
	}

	public Statutcandidat(Integer id, String intitule, Integer beneficiaireniveau, Set<Candidat> candidats) {
		this.id = id;
		this.intitule = intitule;
		this.beneficiaireniveau = beneficiaireniveau;
		//this.candidats = candidats;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "INTITULE", length = 1024)
	public String getIntitule() {
		return this.intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	@Column(name = "BENEFICIAIRENIVEAU", precision = 22, scale = 0)
	public Integer getBeneficiaireniveau() {
		return this.beneficiaireniveau;
	}

	public void setBeneficiaireniveau(Integer beneficiaireniveau) {
		this.beneficiaireniveau = beneficiaireniveau;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statutcandidat")
	public Set<Candidat> getCandidats() {
		return this.candidats;
	}

	public void setCandidats(Set<Candidat> candidats) {
		this.candidats = candidats;
	}

}
