package com.pej.domains;
// Generated 30 oct. 2016 22:13:12 by Hibernate Tools 5.2.0.Beta1



import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.pej.domains.Formation;

/**
 * Typeformation generated by hbm2java
 */
@Entity
@Table(name="TYPEFORMATION"
)
public class Typeformation  implements java.io.Serializable {


     private Integer idtypeformation;
     private String intitule;
 	private String description;
 	private String nature;
 	private Set<Formation> formations = new HashSet<Formation>(0);

 	public Typeformation() {
 	}

 	public Typeformation(Integer idtypeformation) {
 		this.idtypeformation = idtypeformation;
 	}

 	public Typeformation(Integer idtypeformation, String intitule, String description, String nature,
 			Set<Formation> formations) {
 		this.idtypeformation = idtypeformation;
 		this.intitule = intitule;
 		this.description = description;
 		this.nature = nature;
 		this.formations = formations;
 	}

   
     @Id
 	@GeneratedValue(generator = "SEQ_IDTYPEFORMATION", strategy = GenerationType.SEQUENCE)
  	@SequenceGenerator(name = "SEQ_IDTYPEFORMATION", sequenceName = "SEQ_IDTYPEFORMATION",allocationSize=1)
    @Column(name="IDTYPEFORMATION", unique=true, nullable=false, precision=22, scale=0)
    public Integer getIdtypeformation() {
        return this.idtypeformation;
    }
    
     public void setIdtypeformation(Integer idtypeformation) {
 		this.idtypeformation = idtypeformation;
 	}

 	@Column(name = "INTITULE", length = 1024)
 	public String getIntitule() {
 		return this.intitule;
 	}

 	public void setIntitule(String intitule) {
 		this.intitule = intitule;
 	}

 	@Column(name = "DESCRIPTION")
 	public String getDescription() {
 		return this.description;
 	}

 	public void setDescription(String description) {
 		this.description = description;
 	}

 	@Column(name = "NATURE")
 	public String getNature() {
 		return this.nature;
 	}

 	public void setNature(String nature) {
 		this.nature = nature;
 	}

 	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeformation")
 	public Set<Formation> getFormations() {
 		return this.formations;
 	}

 	public void setFormations(Set<Formation> formations) {
 		this.formations = formations;
 	}


}


