package com.pej.domains;
// Generated 30 oct. 2016 22:13:12 by Hibernate Tools 5.2.0.Beta1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Typeformation generated by hbm2java
 */
@Entity
@Table(name="TYPEFORMATION"
    ,schema="ADMINPEJ"
)
public class Typeformation  implements java.io.Serializable {


     private BigDecimal idtypeformation;
     private String intitule;
     private String description;
     private String nature;

    public Typeformation() {
    }

	
    public Typeformation(BigDecimal idtypeformation) {
        this.idtypeformation = idtypeformation;
    }
    public Typeformation(BigDecimal idtypeformation, String intitule, String description, String nature) {
       this.idtypeformation = idtypeformation;
       this.intitule = intitule;
       this.description = description;
       this.nature = nature;
    }
   
     @Id 

    
    @Column(name="IDTYPEFORMATION", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdtypeformation() {
        return this.idtypeformation;
    }
    
    public void setIdtypeformation(BigDecimal idtypeformation) {
        this.idtypeformation = idtypeformation;
    }

    
    @Column(name="INTITULE", length=20)
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="NATURE")
    public String getNature() {
        return this.nature;
    }
    
    public void setNature(String nature) {
        this.nature = nature;
    }




}


