package com.pej.domains;
// Generated 12 nov. 2016 14:53:17 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * UsersRole generated by hbm2java
 */
@Entity
@Table(name = "USERS_ROLE")
public class UsersRole implements java.io.Serializable {

	private Integer idusersrole;
	private Utilisateur utilisateur;
	private Roles roles;

	public UsersRole() {
	}

	public UsersRole(Integer idusersrole) {
		this.idusersrole = idusersrole;
	}

	public UsersRole(Integer idusersrole, Utilisateur utilisateur, Roles roles) {
		this.idusersrole = idusersrole;
		this.utilisateur = utilisateur;
		this.roles = roles;
	}

	@Id
  	@GeneratedValue(generator = "SEQ_IDUSERSROLE", strategy = GenerationType.SEQUENCE)
  	@SequenceGenerator(name = "SEQ_IDUSERSROLE", sequenceName = "SEQ_IDUSERSROLE",allocationSize=1)
	@Column(name = "IDUSERSROLE", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdusersrole() {
		return this.idusersrole;
	}

	public void setIdusersrole(Integer idusersrole) {
		this.idusersrole = idusersrole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUSERS")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDROLES")
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

}
