package com.pej.domains;
// Generated 21 nov. 2016 18:31:37 by Hibernate Tools 5.2.0.Beta1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "UTILISATEUR")
public class Utilisateur implements java.io.Serializable {

	private Integer idusers;
	private String username;
	private String password;
	private String firstname;
	private String lastname;
	private String email;
	private Integer enabled;
	private Date datecreated;
	private Date datemodified;
	private String roleName;
	private Set<UsersRole> usersRoles = new HashSet<UsersRole>(0);

	public Utilisateur() {
	}

	public Utilisateur(Integer idusers) {
		this.idusers = idusers;
	}

	public Utilisateur(Integer idusers, String username, String password, String firstname, String lastname,
			Integer enabled, Date datecreated, Date datemodified, Set<UsersRole> usersRoles) {
		this.idusers = idusers;
		this.username = username;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.enabled = enabled;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.usersRoles = usersRoles;
	}

	@Id
  	@GeneratedValue(generator = "SEQ_IDUSERS", strategy = GenerationType.SEQUENCE)
  	@SequenceGenerator(name = "SEQ_IDUSERS", sequenceName = "SEQ_IDUSERS",allocationSize=1)
	@Column(name = "IDUSERS", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdusers() {
		return this.idusers;
	}

	public void setIdusers(Integer idusers) {
		this.idusers = idusers;
	}

	@Column(name = "USERNAME", unique = true, nullable = false, length = 1024)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", length = 1024)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "FIRSTNAME", length = 1024)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "LASTNAME", length = 1024)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "EMAIL", length = 1024)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ENABLED", precision = 22, scale = 0)
	public Integer getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATECREATED", length = 7)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEMODIFIED", length = 7)
	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<UsersRole> getUsersRoles() {
		return this.usersRoles;
	}

	public void setUsersRoles(Set<UsersRole> usersRoles) {
		this.usersRoles = usersRoles;
	}

    @Transient
	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
}
